<?php

/**
 * @file
 * Contains commerce_abandoned_carts.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Theme\ThemeManagerInterface;
use Mirum\Helpers\Helpers;

/**
 * Implements hook_help().
 */
function commerce_abandoned_carts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_abandoned_carts module.
    case 'help.page.commerce_abandoned_carts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Commerce Abandonned Carts') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function commerce_abandoned_carts_theme() {
  return [
    'commerce_abandoned_carts' => [
      'render element' => 'children',
    ],
    'commerce_abandoned_carts_email' => [
      'variables' => [
        'order' => NULL,
        'order_number' => NULL,
        'site_name' => NULL,
        'phone' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function commerce_abandoned_carts_cron() {
  $carts_timeout = \Drupal::config('commerce_abandoned_carts.settings')->get('commerce_abandoned_carts_timeout');
  $carts_timeout = $carts_timeout * 60; // converts minutes to seconds
  $time = REQUEST_TIME;
  $history_limit = \Drupal::config('commerce_abandoned_carts.settings')->get('commerce_abandoned_carts_history_limit');
  $history_limit = $history_limit * 60; // converts minutes to seconds

  $statuses = \Drupal::config('commerce_abandoned_carts.settings')->get('commerce_abandoned_carts_abandoned_statuses');
  foreach ($statuses as $key => $value) {
    if ($value != '') {
      $status[$key] = $value;
    }
  }
  $select = db_select('commerce_order', 'o');
  $select->leftJoin('commerce_abandoned_carts', 'a', 'o.order_id = a.order_id');
  $select->join('commerce_order__field_status', 'l', 'o.order_id = l.entity_id');  // only query for carts that have line items in them

  // Select these specific fields for the output.
  $select->addField('o', 'order_id');
  $select->addField('l', 'field_status_value');
  $select->addField('o', 'mail');
  $select->condition('o.mail', '', '!=')
         ->isNull('a.status')
         ->condition('o.created', $time - $carts_timeout, '<')
         ->condition('o.created', $time - $history_limit, '>=')
         ->condition('l.field_status_value', $statuses, 'IN')
         ->orderBy('o.created', 'ASC');
  $result = $select->execute()->fetchAll(\PDO::FETCH_ASSOC);

  $batch_num = 0;

  foreach ($result as $record) {

    $order =  \Drupal::entityTypeManager()->getStorage('commerce_order')->load($record['order_id']);
    $batch_limit = \Drupal::config('commerce_abandoned_carts.settings')->get('commerce_abandoned_carts_batch_limit');

    // Is TEST mode enabled?
    $test_mode = \Drupal::config('commerce_abandoned_carts.settings')->get('commerce_abandoned_carts_testmode_active');

    if ($test_mode == 1) {
      \Drupal::logger('commerce_abandoned_carts')->notice('Operating in TEST mode.');
      $recipient = \Drupal::config('commerce_abandoned_carts.settings')->get('commerce_abandoned_carts_testmode_email');
    }
    else {
      $recipient = Helpers::getStorageVal($order, 'mail', '');
    }

    // Send email
    $language = \Drupal::currentUser()->getPreferredLangcode();
    global $base_url;

    $from = \Drupal::config('commerce_abandoned_carts.settings')->get('commerce_abandoned_carts_from_email');

    if (empty($from)){
      $from = \Drupal::config()->get('site_mail');
    }
    global $base_url;

    $phone = \Drupal::config('commerce_abandoned_carts.settings')->get('commerce_abandoned_carts_customer_service_phone_number');
    $from_name = \Drupal::config('commerce_abandoned_carts.settings')->get('commerce_abandoned_carts_from_name');

    $params['order'] = $order;
    $params['subject'] = \Drupal::config('commerce_abandoned_carts.settings')->get('commerce_abandoned_carts_subject');
    $params['from_name'] = $from_name;
    $params['reply-to'] = $from;
    // Set up email template
    $body_data = [
       '#theme' => 'commerce_abandoned_carts_email',
       '#order' => $order,
       '#order_number' => $record['order_id'],
       '#site_name' => \Drupal::config('system.site')->get('name'),
       '#phone' => $phone,
    ];

    // Render the template to HTML
    $params['body']  = \Drupal::service('renderer')->renderPlain($body_data)->__toString();;

    $mailManager = \Drupal::service('plugin.manager.mail');
    $module = 'commerce_abandoned_carts';
    $key = 'cac';
    $send = true;
    $result = $mailManager->mail($module, $key, $recipient, $language, $params, NULL, $send);

    // Update record if not in test mode
    if ($test_mode != 1) {
      $nid = db_insert('commerce_abandoned_carts')
        ->fields(array(
          'order_id' => $record['order_id'],
          'status' => 1,
          'timestamp' => REQUEST_TIME,
        ))
        ->execute();
    }

    $batch_num++;
    if ($batch_num >= $batch_limit){
      break;
    }
  }
  \Drupal::logger('commerce_abandoned_carts')->notice('Sent ' . $batch_num . ' abandoned cart emails.');
}

/**
 * Implementation of hook_mail
 */
function commerce_abandoned_carts_mail($key, &$message, $params) {

/*  $langcode = isset($message['language']) ? $message['language']->language : \Drupal::currentUser()->getPreferredLangcode();
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
  $message['subject'] = $params['subject'];

  $from_name = $params['from_name'];
  if (empty($from_name)){
    $from_name = \Drupal::config('system.site')->get('name');
  }

  $message['from'] = $from_name;
  $message['body'] = $params['body'];

  $message['headers']['Reply-To'] =  $params['reply-to'];
  $message['headers']['From'] = $params['reply-to'];
  $message['headers']['Sender'] = $params['reply-to'];
  $message['headers']['Return-Path'] = $params['reply-to'];

  // Send BCC to Admin if activated
  if (\Drupal::config('commerce_abandoned_carts.settings')->get('commerce_abandoned_carts_bcc_active') == 1) {
    $message['headers']['Bcc'] = \Drupal::config('commerce_abandoned_carts.settings')->get('commerce_abandoned_carts_bcc_email');

     if(\Drupal::moduleHandler()->moduleExists('mandrill')){
      $message['to'] = $message['to'] . ',' . \Drupal::config('commerce_abandoned_carts.settings')->get('commerce_abandoned_carts_bcc_email');
      $message['headers']['/X-MC-PreserveRecipients'] = 'False';
    }
  }

  // Strip newline characters from e-mail subjects.
  $message['subject'] = str_replace(array("\r\n", "\r", "\n"), ' ', $message['subject']);

  // Apply an input format to the message body
  $message['body'] = check_markup($message['body'], 'full_html', $langcode);*/
}
